### ISSUE TITLE
Header view sticky goes wrong, when keyboard is opened

### ISSUE THREAD

**Issue by Karthikmoback** [demirciy/TableStickyViewExample#1]
I added your sticky headerview to my table view, Everything works great. Except when when keyboard is opened .
I have a textfield inside by tableview, on editing, keyboard opens up and when i close and scroll to top, the sticky header is showing only view of minimum height value and also table view cells are behind the sticky header view. Please let me know the fix to be taken care inside sticky header view.

**Comment by Karthikmoback** [comment]
If found the bug in my code, i was supposed to save contentInset and set back when keyboard open and close. Apologies , your code was perfect.

**Comment by meyusufdemirci** [comment]
Thanks for your responsibility to open source projects!

None of the code is perfect 😎
